[DEFAULT]
# specify the environment, prod=production , dev = development
env=dev
azure.connectionstring=<connection_string>
influxdb.url=<influxdb_url>
influxdb.org=<influxdb_organization_id>
influxdb.bucket=<influxdb_bucketname>
influxdb.token=<influxdb_token>
