[DEFAULT]
# specify the environment, prod=production , dev = development
env=prod
azure.connectionstring=DefaultEndpointsProtocol=https;AccountName=othellowheatdata;AccountKey=cMkhUO7CSAJ0tk+7Yjh8viqr6EPuLvkwORvVaodsWEKAQ/rPiGfnOqTiVRCdNnOBeHgGldqm323F+AStQboN4g==;EndpointSuffix=core.windows.net
